# Generated by Django 4.1.2 on 2022-10-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('voice_path', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('native_word', models.CharField(max_length=40)),
                ('translate_word', models.CharField(max_length=40)),
                ('add_data', models.DateTimeField()),
                ('last_training_data', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.directory')),
            ],
        ),
    ]
